## 00. Pytorch Fundamentals

In [1]:
# Importing modules
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Introduction to Tensors
# Creating Tensors

In [2]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# get scalar back as pythong int
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[5, 5],
                       [5, 5]])
MATRIX

tensor([[5, 5],
        [5, 5]])

In [9]:
MATRIX.shape

torch.Size([2, 2])

In [10]:
MATRIX.ndim

2

In [11]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [12]:
TENSOR.shape   # means that we have only 3x3 dimension tensor

torch.Size([1, 3, 3])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [15]:
TENSOR[0, 1]

tensor([4, 5, 6])

In [16]:
TENSOR[0, 1, 1]

tensor(5)

# Random Tensors
Why Random Tensors? RT because the way many neural networks learn is that they start with tensors full of random numbers and the adjust those numbers to better represent the data. Start with random numbers -> look at the data -> update random numbers -> look at data -> update random numbers

In [17]:
# Creating a Random Tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.3930, 0.1484, 0.0696, 0.5799],
        [0.6540, 0.7560, 0.5420, 0.0495],
        [0.1980, 0.7815, 0.9714, 0.6073]])

In [18]:
another_random_tensor = torch.rand(1, 3, 4)
another_random_tensor

tensor([[[0.4119, 0.3860, 0.4481, 0.3153],
         [0.9018, 0.0831, 0.1493, 0.8636],
         [0.0385, 0.5544, 0.3826, 0.4121]]])

In [19]:
another_random_tensor.ndim

3

In [20]:
# Creating a random tensor to an image tensor
random_size_image_tensor = torch.rand(size = (224, 224, 3)) # height, width, color channels
random_size_image_tensor

tensor([[[0.1186, 0.9115, 0.1671],
         [0.5388, 0.3910, 0.8491],
         [0.8785, 0.2504, 0.9269],
         ...,
         [0.0591, 0.0645, 0.4383],
         [0.8503, 0.7009, 0.0691],
         [0.8888, 0.9170, 0.4282]],

        [[0.3776, 0.3869, 0.5531],
         [0.1373, 0.3370, 0.3196],
         [0.4369, 0.8302, 0.8595],
         ...,
         [0.2371, 0.7806, 0.2976],
         [0.2917, 0.0414, 0.8920],
         [0.9222, 0.6185, 0.5648]],

        [[0.1801, 0.5697, 0.0667],
         [0.0636, 0.4056, 0.2375],
         [0.2114, 0.7313, 0.3436],
         ...,
         [0.3362, 0.4099, 0.4323],
         [0.1385, 0.5402, 0.0749],
         [0.5183, 0.4183, 0.9181]],

        ...,

        [[0.2513, 0.5210, 0.0654],
         [0.7032, 0.0176, 0.8018],
         [0.9246, 0.1692, 0.7686],
         ...,
         [0.5583, 0.6399, 0.4882],
         [0.5221, 0.2273, 0.8638],
         [0.0071, 0.0493, 0.8369]],

        [[0.1106, 0.1553, 0.0501],
         [0.8853, 0.0626, 0.0832],
         [0.

In [21]:
random_size_image_tensor.shape

torch.Size([224, 224, 3])

In [22]:
random_size_image_tensor.ndim

3

### Zeros and Ones Tensor

In [23]:
# Creating a tensor of all zeros
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [25]:
# Creating tensor of all ones
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [26]:
ones.dtype

torch.float32

In [27]:
random_tensor.dtype

torch.float32

### Creating a RANGE OF TENSORS and TENSORS-LIKE

In [28]:
# Use Torch.range()
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
torch.arange(start = 0, end = 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
torch.arange(start=0, end=1000, step=5)

tensor([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
         70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125, 130, 135,
        140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190, 195, 200, 205,
        210, 215, 220, 225, 230, 235, 240, 245, 250, 255, 260, 265, 270, 275,
        280, 285, 290, 295, 300, 305, 310, 315, 320, 325, 330, 335, 340, 345,
        350, 355, 360, 365, 370, 375, 380, 385, 390, 395, 400, 405, 410, 415,
        420, 425, 430, 435, 440, 445, 450, 455, 460, 465, 470, 475, 480, 485,
        490, 495, 500, 505, 510, 515, 520, 525, 530, 535, 540, 545, 550, 555,
        560, 565, 570, 575, 580, 585, 590, 595, 600, 605, 610, 615, 620, 625,
        630, 635, 640, 645, 650, 655, 660, 665, 670, 675, 680, 685, 690, 695,
        700, 705, 710, 715, 720, 725, 730, 735, 740, 745, 750, 755, 760, 765,
        770, 775, 780, 785, 790, 795, 800, 805, 810, 815, 820, 825, 830, 835,
        840, 845, 850, 855, 860, 865, 870, 875, 880, 885, 890, 8

In [31]:
# create a range -
one_to_ten = torch.arange(1, 11, 1)

In [32]:
# now make a similar shape tensor with ZEROS in it
ten_zeros = torch.zeros_like( input = one_to_ten )
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [33]:
# similarly create a similar shape tensor with only ones
ten_ones = torch.ones_like( input = one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Tensor Datatypes

**Note**: Tensor datatypes is one of the 3 big errors that you will run into while using PyTorch for deep learning:
1. Tensor not right datatype
2. Tensor not right shape
3. Tensor not on the right device

In [34]:
# Float 32 Tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None)
float_32_tensor

tensor([3., 6., 9.])

In [35]:
float_32_tensor.dtype   # even if dtype = None, default tensor data type is Float32

torch.float32

In [36]:
new_float = torch.tensor([4.0, 6.0, 8.0], dtype = torch.float16)
new_float

tensor([4., 6., 8.], dtype=torch.float16)

In [37]:
new_float.dtype

torch.float16

In [38]:
complete_float = torch.tensor([1.0, 2.0, 3.0],
                              dtype = None,  # what datatype is the tensor (eg. float-32, float-16)
                              device = None,
                              requires_grad = True)
complete_float

tensor([1., 2., 3.], requires_grad=True)

### Getting information from a tensor
1. Tensor not right datatype = to do get datatype from a tensor using `tensor.dtype`.
2. Tensor not right shape = to do get shape from a tensor using `tensor.shape`.  (can also use `tensor.size()`, only difference is that `tensor.size()` is a function whereas `tensor.shape` is an attribute)
3. Tensor not on the right device = to do get device from tensor using `tensor.device`.

In [39]:
# create a random tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.6428, 0.2685, 0.7768, 0.7122],
        [0.7310, 0.3244, 0.7007, 0.8333],
        [0.8488, 0.4975, 0.5005, 0.4285]])

In [40]:
# Find out the details about the tensor
print(some_tensor)
print(f"Datatype of the tensor: {some_tensor.dtype}")
print(f"Shape of the tensor: {some_tensor.shape}")
print(f"Device of the tensor: {some_tensor.device}")

tensor([[0.6428, 0.2685, 0.7768, 0.7122],
        [0.7310, 0.3244, 0.7007, 0.8333],
        [0.8488, 0.4975, 0.5005, 0.4285]])
Datatype of the tensor: torch.float32
Shape of the tensor: torch.Size([3, 4])
Device of the tensor: cpu


### Manipulating Tensors

Tensor Operations Include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [41]:
# Create a Tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])

In [42]:
# Add 10 to the tensor
tensor = tensor + 10
tensor

tensor([11, 12, 13])

In [43]:
# Multiply the tensor with 10
tensor = tensor * 10

In [44]:
tensor

tensor([110, 120, 130])

In [45]:
# Subtract 10 from the tensor
tensor = tensor - 10
tensor

tensor([100, 110, 120])

In [46]:
# Using pyTorch in-built funtions
torch.mul(tensor, 10)     # does not modify the original tensor, returns a new one.

tensor([1000, 1100, 1200])

In [47]:
torch.add(tensor, 100)    # similary this also does not modify the original tensor and instead returns a new one.

tensor([200, 210, 220])

### Matrix Multiplication

Two main types of multiplication is used in neural networks and deep learning: 
1. Element-wise multiplication
2. Matrix Multiplication (dot product)

There are two main rules that matrix multiplication must satisfy:
1. The **inner dimensions** must match
* `(3, 2)` @ `(3, 2)` won't work.
* `(2, 3)` @ `(3, 2)` will work.
* `(3, 2)` @ `(2, 3)` will work.

2. The resulting matrix has a shape of **outer dimensions**:
* `(2, 3)` @ `(3, 2)` --> `(2, 2)`
* `(3, 2)` @ `(2, 3)` --> `(2, 2)`

`@` is another way for matrix multiplication

In [48]:
# Element-wise multiplication
print(tensor, "*",  tensor)
print(f"Equals: {tensor * tensor}")

tensor([100, 110, 120]) * tensor([100, 110, 120])
Equals: tensor([10000, 12100, 14400])


In [49]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(36500)

In [50]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(36500)
CPU times: total: 0 ns
Wall time: 2.45 ms


In [51]:
%%time
torch.matmul(tensor, tensor)    #the matrix multiplication function of torch is much faster than the traditional way of matrix multiplication.

CPU times: total: 0 ns
Wall time: 0 ns


tensor(36500)

### One of the most commong errors in deep learning is SHAPE ERRORS

In [52]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

torch.mm(tensor_A, tensor_B)   # torch.mm() is the same as torch.matmul()
## GIVES SHAPE ERROR

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix our shape errors, we can convert one of the tensors using **transpose**.

A **transpose** switches the axes or the dimensions of a given tensor.

In [53]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [54]:
tensor_B.T     # transposes the tensor_b

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [55]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

# Finding min, max, mean, sum etc (Tensor Aggregation)

In [56]:
# Create a Tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [57]:
# Finding the minimum
torch.min(x), x.min()    # any of the two can be used

(tensor(0), tensor(0))

In [58]:
# Finding the maximum
torch.max(x), x.max()

(tensor(90), tensor(90))

In [59]:
# Finding the mean
torch.mean(x)

# this gives the DATATYPE ERROR (one of the 3 major errors)
# given tensor has the datatype LONG (mean does not work on LONG)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [60]:
# The torch.mean() function requires a tensor of datatype float32
torch.mean(x.type(dtype=torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [61]:
# Finding the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

# Finding the positional min and max

In [62]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [63]:
x.argmin() # gives the index of the minimum element in the tensor

tensor(0)

In [64]:
x.argmax() # gives the index of the maximum element in the tensor

tensor(9)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - Reshapes an input tensor to a defined shape.
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor.
* Stacking - Combine multiple tensors on top of each other (vstack) or side by side (hstack).
* Squeeze - Removes all `1` dimensions from a tensor.
* Unsqueeze - Add a `1` dimension to a target tensor.
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way.

In [65]:
# Create a new tensor
new_tensor = torch.arange(1., 11.)
new_tensor, new_tensor.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [66]:
# add an extra dimension
tensor_reshaped = new_tensor.reshape(1, 10)
tensor_reshaped

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [67]:
tensor_reshaped_again = new_tensor.reshape(5, 2)
tensor_reshaped_again

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [68]:
# Changing the VIEW of the tensor
view_tensor = new_tensor.view(1, 10)
view_tensor

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [70]:
# changind the view changes the original tensor, because view of a tensor shares the same memory as the original tensor.
view_tensor[:, 0] = 5
view_tensor, new_tensor

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [78]:
# Stack tensors on top of each other
new_tensor_stacked = torch.stack([new_tensor, new_tensor, new_tensor, new_tensor], dim=-2)
new_tensor_stacked

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [81]:
# Using VERTICAL STACK OR TORCH.VSTACK
p = torch.arange(1, 6)
q = torch.arange(6, 11)
p, q

(tensor([1, 2, 3, 4, 5]), tensor([ 6,  7,  8,  9, 10]))

In [84]:
# Verticall stacking the tensors
torch.vstack((p, q))

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

In [85]:
# Using HORIZONTAL STACKING OR TORCH.HSTACK
torch.hstack((p, q))

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [89]:
# SQUEEZING 
some_tensor = torch.zeros(2, 1, 2, 1, 2)
some_tensor

tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])

In [90]:
# tensor([ # 1st dimension with 2 subgroups
#         [ # first sub-group with only 1 subgroup inside 2nd DIMENSION
#             [ # 3rd dimension with 2 sub groups
#                 [ # first subgroup 4th DIMENSION
#                     [0., 0.] # 5th DIMENSION
#                 ],

#                 [ # second subgroup
#                     [0., 0.]
#                 ]
#             ]
#         ],

#         [ # second subgroup with only one subgroup inside 2nd DIMESION
#             [ # 3rd dimension with two subgroups
#                 [ # first sub group 4th DIMENSION
#                     [0., 0.] # 5th DIMENSION
#                 ],
#                 [ # second subgroup
#                     [0., 0.]
#                 ]
#             ]
#         ]
#     ])

In [ ]:
# Squeezing
some_tensor.squeeze()

# removes all single dimensions

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [ ]:
# example of squeezing
ek_tensor = torch.arange(1, 11)
ek_tensor

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [95]:
ek_tensor_reshape = ek_tensor.reshape([1, 10])
ek_tensor_reshape

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [99]:
print(f"Original Tensor: {ek_tensor_reshape}")
print(f"Original Tensor Shape: {ek_tensor_reshape.shape}")

print(f"\nSqueezed Tensor: {ek_tensor_reshape.squeeze()}")
print(f"Squeezed Tensor Shape: {ek_tensor_reshape.squeeze().shape}")


# as we can see that the tensor dimension was [1, 10] but after squeezing the tensor the single dimensions were removed, and the tensor has a dimension of only [10].

Original Tensor: tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])
Original Tensor Shape: torch.Size([1, 10])

Squeezed Tensor: tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
Squeezed Tensor Shape: torch.Size([10])


In [102]:
# Making a new tensor for the squeezed tensor
squeezed_tensor = ek_tensor_reshape.squeeze()
squeezed_tensor, squeezed_tensor.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), torch.Size([10]))

In [111]:
# Unsqueezing the squeezed tensor  -  Adds a single dimension to the target tensor at a given specific dimension.
unsqueezed_tensor = squeezed_tensor.unsqueeze(dim=1)
unsqueezed_tensor, unsqueezed_tensor.shape


(tensor([[ 1],
         [ 2],
         [ 3],
         [ 4],
         [ 5],
         [ 6],
         [ 7],
         [ 8],
         [ 9],
         [10]]),
 torch.Size([10, 1]))

In [112]:
print(f"Previous Tensor (Squeezed): {squeezed_tensor}")
print(f"Previous Tensor (Squeezed) Shape: {squeezed_tensor.shape}")

print(f"\nUnsqueezed Tensor: {unsqueezed_tensor}")
print(f"Unsqueezed Tensor Shape: {unsqueezed_tensor.shape}")

Previous Tensor (Squeezed): tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
Previous Tensor (Squeezed) Shape: torch.Size([10])

Unsqueezed Tensor: tensor([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]])
Unsqueezed Tensor Shape: torch.Size([10, 1])


In [124]:
# PERMUTE - rearrages the dimensions of target tensor tensor in a specified order
original_tensor = torch.rand((225, 224, 3))     # [height, width, colour_channels]
print(f"Original Tensor Shape: {original_tensor.shape}")

# rearrange the tensor --->  0 -> 1, 1 -> 2, 2 -> 1
original_tensor_permuted = original_tensor.permute(2, 0, 1)
print(f"Permuted Tensor Shape: {original_tensor_permuted.shape}")

Original Tensor Shape: torch.Size([225, 224, 3])
Permuted Tensor Shape: torch.Size([3, 225, 224])


In [125]:
original_tensor[0, 0, 0] = 23456

In [136]:
original_tensor[0, 0, 0], original_tensor_permuted[0, 0, 0]

(tensor(23456.), tensor(23456.))