## 00. Pytorch Fundamentals

In [133]:
# Importing modules
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Introduction to Tensors
# Creating Tensors

In [134]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [135]:
scalar.ndim

0

In [136]:
# get scalar back as pythong int
scalar.item()

7

In [137]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [138]:
vector.ndim

1

In [139]:
vector.shape

torch.Size([2])

In [140]:
# MATRIX
MATRIX = torch.tensor([[5, 5],
                       [5, 5]])
MATRIX

tensor([[5, 5],
        [5, 5]])

In [141]:
MATRIX.shape

torch.Size([2, 2])

In [142]:
MATRIX.ndim

2

In [143]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [144]:
TENSOR.shape   # means that we have only 3x3 dimension tensor

torch.Size([1, 3, 3])

In [145]:
TENSOR.ndim

3

In [146]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [147]:
TENSOR[0, 1]

tensor([4, 5, 6])

In [148]:
TENSOR[0, 1, 1]

tensor(5)

# Random Tensors
Why Random Tensors? RT because the way many neural networks learn is that they start with tensors full of random numbers and the adjust those numbers to better represent the data. Start with random numbers -> look at the data -> update random numbers -> look at data -> update random numbers

In [149]:
# Creating a Random Tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.7210, 0.2101, 0.3772, 0.4597],
        [0.8983, 0.5461, 0.6287, 0.2150],
        [0.9992, 0.9151, 0.8747, 0.1382]])

In [150]:
another_random_tensor = torch.rand(1, 3, 4)
another_random_tensor

tensor([[[0.7988, 0.5136, 0.8620, 0.6150],
         [0.2036, 0.0989, 0.7114, 0.0170],
         [0.0694, 0.4822, 0.3145, 0.4750]]])

In [151]:
another_random_tensor.ndim

3

In [152]:
# Creating a random tensor to an image tensor
random_size_image_tensor = torch.rand(size = (224, 224, 3)) # height, width, color channels
random_size_image_tensor

tensor([[[0.3274, 0.0870, 0.9230],
         [0.2328, 0.2349, 0.8472],
         [0.3732, 0.6343, 0.3113],
         ...,
         [0.5703, 0.6222, 0.7685],
         [0.6050, 0.0745, 0.0248],
         [0.0955, 0.8633, 0.1506]],

        [[0.9753, 0.8650, 0.2937],
         [0.7916, 0.0905, 0.1128],
         [0.9539, 0.4683, 0.1216],
         ...,
         [0.6961, 0.5276, 0.3107],
         [0.0128, 0.6967, 0.4924],
         [0.4274, 0.8369, 0.4531]],

        [[0.8679, 0.8064, 0.1634],
         [0.1811, 0.3188, 0.0980],
         [0.6689, 0.3211, 0.4886],
         ...,
         [0.5960, 0.4435, 0.3522],
         [0.4026, 0.0476, 0.7128],
         [0.8009, 0.2346, 0.0720]],

        ...,

        [[0.9401, 0.9053, 0.9009],
         [0.4528, 0.9529, 0.8829],
         [0.5514, 0.0079, 0.0857],
         ...,
         [0.0976, 0.1144, 0.1623],
         [0.4106, 0.0867, 0.8192],
         [0.5110, 0.6958, 0.3880]],

        [[0.6535, 0.6049, 0.6623],
         [0.4999, 0.9840, 0.7486],
         [0.

In [153]:
random_size_image_tensor.shape

torch.Size([224, 224, 3])

In [154]:
random_size_image_tensor.ndim

3

### Zeros and Ones Tensor

In [155]:
# Creating a tensor of all zeros
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [156]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [157]:
# Creating tensor of all ones
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [158]:
ones.dtype

torch.float32

In [159]:
random_tensor.dtype

torch.float32

### Creating a RANGE OF TENSORS and TENSORS-LIKE

In [160]:
# Use Torch.range()
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [161]:
torch.arange(start = 0, end = 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [162]:
torch.arange(start=0, end=1000, step=5)

tensor([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
         70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125, 130, 135,
        140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190, 195, 200, 205,
        210, 215, 220, 225, 230, 235, 240, 245, 250, 255, 260, 265, 270, 275,
        280, 285, 290, 295, 300, 305, 310, 315, 320, 325, 330, 335, 340, 345,
        350, 355, 360, 365, 370, 375, 380, 385, 390, 395, 400, 405, 410, 415,
        420, 425, 430, 435, 440, 445, 450, 455, 460, 465, 470, 475, 480, 485,
        490, 495, 500, 505, 510, 515, 520, 525, 530, 535, 540, 545, 550, 555,
        560, 565, 570, 575, 580, 585, 590, 595, 600, 605, 610, 615, 620, 625,
        630, 635, 640, 645, 650, 655, 660, 665, 670, 675, 680, 685, 690, 695,
        700, 705, 710, 715, 720, 725, 730, 735, 740, 745, 750, 755, 760, 765,
        770, 775, 780, 785, 790, 795, 800, 805, 810, 815, 820, 825, 830, 835,
        840, 845, 850, 855, 860, 865, 870, 875, 880, 885, 890, 8

In [163]:
# create a range -
one_to_ten = torch.arange(1, 11, 1)

In [164]:
# now make a similar shape tensor with ZEROS in it
ten_zeros = torch.zeros_like( input = one_to_ten )
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [165]:
# similarly create a similar shape tensor with only ones
ten_ones = torch.ones_like( input = one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Tensor Datatypes

**Note**: Tensor datatypes is one of the 3 big errors that you will run into while using PyTorch for deep learning:
1. Tensor not right datatype
2. Tensor not right shape
3. Tensor not on the right device

In [166]:
# Float 32 Tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None)
float_32_tensor

tensor([3., 6., 9.])

In [167]:
float_32_tensor.dtype   # even if dtype = None, default tensor data type is Float32

torch.float32

In [168]:
new_float = torch.tensor([4.0, 6.0, 8.0], dtype = torch.float16)
new_float

tensor([4., 6., 8.], dtype=torch.float16)

In [169]:
new_float.dtype

torch.float16

In [170]:
complete_float = torch.tensor([1.0, 2.0, 3.0],
                              dtype = None,  # what datatype is the tensor (eg. float-32, float-16)
                              device = None,
                              requires_grad = True)
complete_float

tensor([1., 2., 3.], requires_grad=True)

### Getting information from a tensor
1. Tensor not right datatype = to do get datatype from a tensor using `tensor.dtype`.
2. Tensor not right shape = to do get shape from a tensor using `tensor.shape`.  (can also use `tensor.size()`, only difference is that `tensor.size()` is a function whereas `tensor.shape` is an attribute)
3. Tensor not on the right device = to do get device from tensor using `tensor.device`.

In [171]:
# create a random tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.9231, 0.0675, 0.6848, 0.8685],
        [0.3593, 0.8516, 0.7116, 0.3774],
        [0.8191, 0.4243, 0.1262, 0.2069]])

In [172]:
# Find out the details about the tensor
print(some_tensor)
print(f"Datatype of the tensor: {some_tensor.dtype}")
print(f"Shape of the tensor: {some_tensor.shape}")
print(f"Device of the tensor: {some_tensor.device}")

tensor([[0.9231, 0.0675, 0.6848, 0.8685],
        [0.3593, 0.8516, 0.7116, 0.3774],
        [0.8191, 0.4243, 0.1262, 0.2069]])
Datatype of the tensor: torch.float32
Shape of the tensor: torch.Size([3, 4])
Device of the tensor: cpu


### Manipulating Tensors

Tensor Operations Include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [173]:
# Create a Tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])

In [174]:
# Add 10 to the tensor
tensor = tensor + 10
tensor

tensor([11, 12, 13])

In [175]:
# Multiply the tensor with 10
tensor = tensor * 10

In [176]:
tensor

tensor([110, 120, 130])

In [177]:
# Subtract 10 from the tensor
tensor = tensor - 10
tensor

tensor([100, 110, 120])

In [178]:
# Using pyTorch in-built funtions
torch.mul(tensor, 10)     # does not modify the original tensor, returns a new one.

tensor([1000, 1100, 1200])

In [179]:
torch.add(tensor, 100)    # similary this also does not modify the original tensor and instead returns a new one.

tensor([200, 210, 220])

### Matrix Multiplication

Two main types of multiplication is used in neural networks and deep learning: 
1. Element-wise multiplication
2. Matrix Multiplication (dot product)

There are two main rules that matrix multiplication must satisfy:
1. The **inner dimensions** must match
* `(3, 2)` @ `(3, 2)` won't work.
* `(2, 3)` @ `(3, 2)` will work.
* `(3, 2)` @ `(2, 3)` will work.

2. The resulting matrix has a shape of **outer dimensions**:
* `(2, 3)` @ `(3, 2)` --> `(2, 2)`
* `(3, 2)` @ `(2, 3)` --> `(2, 2)`

`@` is another way for matrix multiplication

In [180]:
# Element-wise multiplication
print(tensor, "*",  tensor)
print(f"Equals: {tensor * tensor}")

tensor([100, 110, 120]) * tensor([100, 110, 120])
Equals: tensor([10000, 12100, 14400])


In [181]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(36500)

In [182]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(36500)
CPU times: total: 0 ns
Wall time: 1.29 ms


In [183]:
%%time
torch.matmul(tensor, tensor)    #the matrix multiplication function of torch is much faster than the traditional way of matrix multiplication.

CPU times: total: 0 ns
Wall time: 0 ns


tensor(36500)

### One of the most commong errors in deep learning is SHAPE ERRORS

In [184]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

torch.mm(tensor_A, tensor_B)   # torch.mm() is the same as torch.matmul()
## GIVES SHAPE ERROR

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix our shape errors, we can convert one of the tensors using **transpose**.

A **transpose** switches the axes or the dimensions of a given tensor.

In [80]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [79]:
tensor_B.T     # transposes the tensor_b

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [186]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])