# Exercises and Extra-Curriculum

In [13]:
import torch
import numpy as np

In [14]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")


# QUESTION 1 - READ DOCUMENTATION

In [15]:
RANDOM_SEED1 = 0
# QUESTION 2 - Create a random tensor with shape (7, 7).
question_2_tensor = torch.rand(7, 7)
question_2_tensor

tensor([[0.0518, 0.4681, 0.6738, 0.3315, 0.7837, 0.5631, 0.7749],
        [0.8208, 0.2793, 0.6817, 0.2837, 0.6567, 0.2388, 0.7313],
        [0.6012, 0.3043, 0.2548, 0.6294, 0.9665, 0.7399, 0.4517],
        [0.4757, 0.7842, 0.1525, 0.6662, 0.3343, 0.7893, 0.3216],
        [0.5247, 0.6688, 0.8436, 0.4265, 0.9561, 0.0770, 0.4108],
        [0.0014, 0.5414, 0.6419, 0.2976, 0.7077, 0.4189, 0.0655],
        [0.8839, 0.8083, 0.7528, 0.8988, 0.6839, 0.7658, 0.9149]])

In [16]:
# QUESTION 3 - Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).
question_3_tensor = torch.rand(1, 7)
answer = torch.matmul(question_2_tensor, question_3_tensor.T)
answer

tensor([[1.6249],
        [1.6406],
        [1.7639],
        [1.3974],
        [1.4691],
        [0.9267],
        [2.4269]])

In [17]:
# QUESTION 4 - Set the random seed to 0 and do exercises 2 & 3 over again.
torch.manual_seed(RANDOM_SEED1)
question_2_tensor = torch.rand(7, 7)

torch.manual_seed(RANDOM_SEED1)
question_3_tensor = torch.rand(1, 7)

answer = torch.mm(question_2_tensor, question_3_tensor.T)
answer

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

In [18]:
# QUESTION 5 - set the random seed of the GPU to 1234
RANDOM_SEED_GPU = 1234
torch.cuda.manual_seed(RANDOM_SEED_GPU)
question_5_tensor = torch.rand(7, 7)

torch.cuda.manual_seed(RANDOM_SEED_GPU)
question_5a_tensor = torch.rand(1, 7)

torch.mm(question_5_tensor, question_5a_tensor.T)

tensor([[1.1061],
        [0.9868],
        [1.8999],
        [0.7716],
        [1.3174],
        [1.6353],
        [1.7395]])

In [19]:
# QUESTION 6 - Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).
torch.manual_seed(1234)
question_6_tensor_A = torch.rand(2, 3, device=device)
question_6_tensor_A = question_6_tensor_A.to(device)

torch.manual_seed(1234)
question_6_tensor_B = torch.rand(2, 3)
question_6_tensor_B = question_6_tensor_B.to(device)

question_6_tensor_A, question_6_tensor_B, question_6_tensor_A.device, question_6_tensor_B.device

(tensor([[0.1272, 0.8167, 0.5440],
         [0.6601, 0.2721, 0.9737]], device='cuda:0'),
 tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 device(type='cuda', index=0),
 device(type='cuda', index=0))

In [20]:
torch.cuda.get_device_name()

'NVIDIA GeForce RTX 3050 Laptop GPU'