## 00. Pytorch Fundamentals

In [5]:
# Importing modules
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Introduction to Tensors
# Creating Tensors

In [2]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [8]:
# get scalar back as pythong int
scalar.item()

7

In [9]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [10]:
vector.ndim

1

In [11]:
vector.shape

torch.Size([2])

In [12]:
# MATRIX
MATRIX = torch.tensor([[5, 5],
                       [5, 5]])
MATRIX

tensor([[5, 5],
        [5, 5]])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
MATRIX.ndim

2

In [15]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [16]:
TENSOR.shape   # means that we have only 3x3 dimension tensor

torch.Size([1, 3, 3])

In [19]:
TENSOR.ndim

3

In [20]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [22]:
TENSOR[0, 1]

tensor([4, 5, 6])

In [23]:
TENSOR[0, 1, 1]

tensor(5)

# Random Tensors
Why Random Tensors? RT because the way many neural networks learn is that they start with tensors full of random numbers and the adjust those numbers to better represent the data. Start with random numbers -> look at the data -> update random numbers -> look at data -> update random numbers

In [18]:
# Creating a Random Tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.5701, 0.3134, 0.6216, 0.1010],
        [0.0213, 0.3016, 0.9873, 0.5434],
        [0.9990, 0.4531, 0.1452, 0.1469]])

In [24]:
another_random_tensor = torch.rand(1, 3, 4)
another_random_tensor

tensor([[[0.9926, 0.0508, 0.9165, 0.9060],
         [0.5174, 0.4859, 0.5853, 0.6134],
         [0.9689, 0.5963, 0.0711, 0.7208]]])

In [25]:
another_random_tensor.ndim

3

In [28]:
# Creating a random tensor to an image tensor
random_size_image_tensor = torch.rand(size = (224, 224, 3)) # height, width, color channels
random_size_image_tensor

tensor([[[0.5682, 0.4481, 0.2437],
         [0.5151, 0.5341, 0.2220],
         [0.2186, 0.7200, 0.6627],
         ...,
         [0.7526, 0.1558, 0.2997],
         [0.2726, 0.2466, 0.8272],
         [0.0614, 0.8488, 0.3190]],

        [[0.7132, 0.3310, 0.2812],
         [0.9600, 0.9514, 0.0140],
         [0.6414, 0.3357, 0.5597],
         ...,
         [0.3501, 0.8765, 0.8737],
         [0.5276, 0.7432, 0.2588],
         [0.0799, 0.9108, 0.2726]],

        [[0.4376, 0.6514, 0.0734],
         [0.0368, 0.2642, 0.9301],
         [0.2230, 0.7218, 0.2808],
         ...,
         [0.3908, 0.2128, 0.3231],
         [0.1583, 0.5956, 0.6192],
         [0.8402, 0.8692, 0.5507]],

        ...,

        [[0.9323, 0.6942, 0.8006],
         [0.8652, 0.9476, 0.3480],
         [0.0578, 0.3774, 0.6333],
         ...,
         [0.0277, 0.1448, 0.1607],
         [0.8572, 0.5520, 0.7912],
         [0.2650, 0.1738, 0.3373]],

        [[0.4337, 0.0358, 0.7778],
         [0.2120, 0.2103, 0.3670],
         [0.

In [29]:
random_size_image_tensor.shape

torch.Size([224, 224, 3])

In [30]:
random_size_image_tensor.ndim

3

### Zeros and Ones Tensor

In [31]:
# Creating a tensor of all zeros
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [32]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [33]:
# Creating tensor of all ones
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [34]:
ones.dtype

torch.float32

In [35]:
random_tensor.dtype

torch.float32

### Creating a RANGE OF TENSORS and TENSORS-LIKE

In [36]:
# Use Torch.range()
torch.arange(0, 10)

C:\Users\malha\AppData\Local\Temp\ipykernel_26028\2818328753.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [38]:
torch.arange(start = 0, end = 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
torch.arange(start=0, end=1000, step=5)

tensor([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
         70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125, 130, 135,
        140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190, 195, 200, 205,
        210, 215, 220, 225, 230, 235, 240, 245, 250, 255, 260, 265, 270, 275,
        280, 285, 290, 295, 300, 305, 310, 315, 320, 325, 330, 335, 340, 345,
        350, 355, 360, 365, 370, 375, 380, 385, 390, 395, 400, 405, 410, 415,
        420, 425, 430, 435, 440, 445, 450, 455, 460, 465, 470, 475, 480, 485,
        490, 495, 500, 505, 510, 515, 520, 525, 530, 535, 540, 545, 550, 555,
        560, 565, 570, 575, 580, 585, 590, 595, 600, 605, 610, 615, 620, 625,
        630, 635, 640, 645, 650, 655, 660, 665, 670, 675, 680, 685, 690, 695,
        700, 705, 710, 715, 720, 725, 730, 735, 740, 745, 750, 755, 760, 765,
        770, 775, 780, 785, 790, 795, 800, 805, 810, 815, 820, 825, 830, 835,
        840, 845, 850, 855, 860, 865, 870, 875, 880, 885, 890, 8

In [43]:
# create a range -
one_to_ten = torch.arange(1, 11, 1)

In [44]:
# now make a similar shape tensor with ZEROS in it
ten_zeros = torch.zeros_like( input = one_to_ten )
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [45]:
# similarly create a similar shape tensor with only ones
ten_ones = torch.ones_like( input = one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Tensor Datatypes

**Note**: Tensor datatypes is one of the 3 big errors that you will run into while using PyTorch for deep learning:
1. Tensor not right datatype
2. Tensor not right shape
3. Tensor not on the right device

In [46]:
# Float 32 Tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None)
float_32_tensor

tensor([3., 6., 9.])

In [47]:
float_32_tensor.dtype   # even if dtype = None, default tensor data type is Float32

torch.float32

In [48]:
new_float = torch.tensor([4.0, 6.0, 8.0], dtype = torch.float16)
new_float

tensor([4., 6., 8.], dtype=torch.float16)

In [49]:
new_float.dtype

torch.float16

In [51]:
complete_float = torch.tensor([1.0, 2.0, 3.0],
                              dtype = None,  # what datatype is the tensor (eg. float-32, float-16)
                              device = None,
                              requires_grad = True)
complete_float

tensor([1., 2., 3.], requires_grad=True)

### Getting information from a tensor
1. Tensor not right datatype = to do get datatype from a tensor using `tensor.dtype`.
2. Tensor not right shape = to do get shape from a tensor using `tensor.shape`.  (can also use `tensor.size()`, only difference is that `tensor.size()` is a function whereas `tensor.shape` is an attribute)
3. Tensor not on the right device = to do get device from tensor using `tensor.device`.

In [53]:
# create a random tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.1832, 0.5737, 0.4556, 0.3839],
        [0.4076, 0.2906, 0.7135, 0.8001],
        [0.7221, 0.2380, 0.4464, 0.4820]])

In [54]:
# Find out the details about the tensor
print(some_tensor)
print(f"Datatype of the tensor: {some_tensor.dtype}")
print(f"Shape of the tensor: {some_tensor.shape}")
print(f"Device of the tensor: {some_tensor.device}")

tensor([[0.1832, 0.5737, 0.4556, 0.3839],
        [0.4076, 0.2906, 0.7135, 0.8001],
        [0.7221, 0.2380, 0.4464, 0.4820]])
Datatype of the tensor: torch.float32
Shape of the tensor: torch.Size([3, 4])
Device of the tensor: cpu


### Manipulating Tensors

Tensor Operations Include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [64]:
# Create a Tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])

In [65]:
# Add 10 to the tensor
tensor = tensor + 10
tensor

tensor([11, 12, 13])

In [66]:
# Multiply the tensor with 10
tensor = tensor * 10

In [67]:
tensor

tensor([110, 120, 130])

In [68]:
# Subtract 10 from the tensor
tensor = tensor - 10
tensor

tensor([100, 110, 120])

In [69]:
# Using pyTorch in-built funtions
torch.mul(tensor, 10)     # does not modify the original tensor, returns a new one.

tensor([1000, 1100, 1200])